# Generated by Django 4.2 on 2025-05-03 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tripimage',
            name='trip',
        ),
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='Trip',
        ),
        migrations.DeleteModel(
            name='TripImage',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
